update workflow's assets from vars

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -12,10 +12,19 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Check if AssetsRepo is set
+        run: |
+          if [ -z "${{ vars.ASSETS_REPO }}" ]; then
+            echo "Error: ASSETS_REPO is not set"
+            exit 1
+          fi
+
       - uses: actions/checkout@v4
         with:
-          repository: tool-jx3/Assets
+          repository: ${{ vars.ASSETS_REPO }}
           path: Assets
+
       - name: Setup golang
         uses: actions/setup-go@v5
         with:
